name: icloudmusic
description: "这是一个可萌的音乐播放器"
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sqflite: ^1.1.3
  dio: ^1.0.9
  flushbar: ^1.4.0
  video_player: ^0.6.4
  flutter_swiper : ^1.1.6
  country_pickers: ^1.0.4
  flutter_spinkit: ^3.1.0
  flare_flutter: ^1.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/video/splash.mp4
    - assets/video/splash1.mp4
    - assets/images/splash.png
    - assets/images/show.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/cn.png

  fonts:
    - family: SF-UI-Display-Regular
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.otf

    - family: SF-UI-Display-Medium
      fonts:
        - asset: assets/fonts/SF-UI-Display-Medium.otf
