name: icloudmusic
description: "这是一个可萌的音乐播放器"

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sqflite: ^1.1.8
  dio: ^3.0.7
  flushbar: ^1.9.1
  video_player: ^0.10.5
  flutter_swiper: ^1.1.6
  country_pickers: ^1.1.0
  flutter_sound: ^1.6.0
  xlive_switch: ^1.0.5
  groovin_widgets: ^1.4.2
  wave: ^0.0.8
  flare_flutter: ^1.8.1
  webview_flutter: ^0.3.18+1
  flutter_easyrefresh: ^2.0.5
  bubble_bottom_bar: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/flare/
    - assets/video/
    - assets/images/

  fonts:
    - family: SF-UI-Display-Regular
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.otf
    - family: SF-UI-Display-Medium
      fonts:
        - asset: assets/fonts/SF-UI-Display-Medium.otf
    - family: SF-UI-Display-Semibold
      fonts:
        - asset: assets/fonts/SF-UI-Display-Semibold.otf
    - family: SF-UI-Display-Bold
      fonts:
        - asset: assets/fonts/SF-UI-Display-Bold.otf
    - family: SF-UI-Display-Black
      fonts:
        - asset: assets/fonts/SF-UI-Display-Black.otf
    - family: SF-UI-Display-Heavy
      fonts:
        - asset: assets/fonts/SF-UI-Display-Heavy.otf
    - family: SF-UI-Display-Light
      fonts:
        - asset: assets/fonts/SF-UI-Display-Light.otf
    - family: SF-UI-Display-Thin
      fonts:
        - asset: assets/fonts/SF-UI-Display-Thin.otf
    - family: SF-UI-Display-Ultralight
      fonts:
        - asset: assets/fonts/SF-UI-Display-Ultralight.otf